use_frameworks!

platform :ios, '8.0'

target 'MTTakePhotoLib_Example' do
  pod 'MTTakePhotoLib', :path => '../'

  target 'MTTakePhotoLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
